//import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Others/Header/Header";
import { AppProvider } from "@/app/utils/Contexts";
import Sidebar from "@/app/components/Others/Sidebar/Sidebar";
import EventModal from "@/app/components/Modals/EventModal/EventModal";
import AddSubjectModal from "@/app/components/Modals/AddSubjectModal/AddSubjectModal";
import JoinGroupModal from "@/app/components/Modals/JoinGroupModal/JoinGroupModal";
import TopNotification from "@/app/components/Modals/TopNotification/TopNotification";
import ChatModal from "@/app/components/Modals/ChatModal/ChatModal";
import NotificationModal from "@/app/components/Modals/NotificationModal/NotificationModal";
import AccountModal from "@/app/components/Modals/AccountModal/AccountModal";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Header />
          <EventModal />
          <ChatModal />
          <AccountModal />
          <TopNotification />
          <JoinGroupModal />
          <AddSubjectModal />
          <NotificationModal />
          {children}
          <Sidebar />
        </AppProvider>
      </body>
    </html>
  );
}
