//import { Inter } from "next/font/google";
//import "./globals.css";
//import Header from "@/Components/Others/Header/Header";
import { AppProvider } from "@/utils/Contexts";
//import Sidebar from "@/Components/Others/Sidebar/Sidebar";
//import EventModal from "@/Components/Modals/EventModal/EventModal";
//import AddSubjectModal from "@/Components/Modals/AddSubjectModal/AddSubjectModal";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          {/* <Header />
          <EventModal /> */}
          {/* <AddSubjectModal /> */}
          {children}
          {/* <Sidebar /> */}
        </AppProvider>
      </body>
    </html>
  );
}
