const Quotes = [
    "\"We are what we repeatedly do. Excellence, then, is not an act, but a habit.\" -Will Durant",
    "\"A habit cannot be tossed out the window; it must be coaxed down the stairs a step at a time.\" -Mark Twain",
    "\"And once you understand that habits can change, you have the freedom and the responsibility to remake them.\" -Charles Duhigg",
    "\"Discipline is choosing between what you want now and what you want most.\" -Abraham Lincoln",
    "\"Drop by drop is the water pot filled.\" -Buddha",
    "\"Feeling sorry for yourself, and your present condition is not only a waste of energy but the worst habit you could possibly have.\" -Dale Carnegie",
    "\"First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not.\" -Octavia Butler",
    "\"Good habits are worth being fanatical about.\" -John Irving",
    "\"Good habits formed at youth make all the difference.\" -Aristotle",
    "\"Habit is the intersection of knowledge (what to do), skill (how to do), and desire (want to do).\" -Stephen R. Covey",
    "\"Habits change into character.\" -Ovid",
    "\"Happiness is a habit—cultivate it.\" -Elbert Hubbard",
    "\"If you are going to achieve excellence in big things, you develop the habit in little matters. Excellence is not an exception, it is a prevailing attitude.\" -Colin Powell",
    "\"Let today be the day you give up who you've been for who you can become.\" -Hal Elrod",
    "\"Life is habit. Or rather life is a succession of habits.\" -Samuel Beckett",
    "\"Motivation is what gets you started. Habit is what keeps you going.\" - Jim Rohn",
    "\"Practice isn't the thing you do once you're good. It's the thing you do that makes you good.\" -Malcolm Gladwell",
    "\"Success is the sum of small efforts repeated day in and day out.\" -Robert Collier",
    "\"Successful people are simply those with successful habits.\" -Brian Tracy",
    "\"The trick to success is to choose the right habit and bring just enough discipline to establish it.\" -Gary Keller and Jay Papasan",
    "\"The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.\" -Albert Einstein",
    "\"There is no elevator to success, you have to take the stairs.\" -Zig Ziglar",
    "\"We are our own potters; for our habits make us, and we make our habits.\" -Frederick Langbridge",
    "\"You'll never change your life until you change something you do daily. The secret of your success is found in your daily routine.\" -John C. Maxwell",
    "\"Nobody can go back and start a new beginning, but anyone can start today and make a new ending.\" — Maria Robinson",
    "\"Success is not final, failure is not fatal: it is the courage to continue that counts.\" -Winston Churchill",
    "\"Learning is the only thing the mind never exhausts, never fears, and never regrets.\" -Leonardo da Vinci.",
    "\"Success isn't overnight. It's when every day you get a little better than the day before. It all adds up.\" -Dwayne Johnson",
    "\"You cannot swim for new horizons until you have the courage to lose sight of the shore.\" -William Faulkner",
    "\"You don't learn to walk by following rules. You learn by doing, and falling over.\" -Richard Branson",
    "\"No matter how busy you may think you are, you must find time for reading, or surrender yourself to self-chosen ignorance.\" -Atwood H. Townsend",
    "\"Never let your persistence and passion turn into stubbornness and ignorance.\" -Anthony J. D'Angelo",
    "\"The best way out is always through.\" - Robert Frost",
    "\"No matter how much falls on us, we keep plowing ahead. That's the only way to keep the roads clear.\" - Greg Kincaid",
    "\"Ambition is the path to success. Persistence is the vehicle you arrive in.\" -Bill Bradley"
]
export {Quotes};